spring:
  shardingsphere:
    mode:
      type: Memory
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://83.229.122.117:3306/sharding_db?serverTimezone=UTC&useSSL=false
        username:
        password:
    sharding:
      tables:
        t_order:
          actual-data-nodes: ds0.t_order_$->{202501..202512}
          table-strategy:
            standard:
              sharding-column: create_time
              precise-algorithm-class-name: com.example.demo.algorithm.MonthShardingAlgorithm
    props:
      sql-show: true